### PR TITLE
Remove whitelisting of functions

### PR DESCRIPTION
**Pull request by NilsIrl**
This decreases build time and prevents functions that should be
whitelisted to not be.

For example, when working on my fork of the leptess API, I didn't have access to the file format enums.

And anyway, `<leptonica/allheaders.h>` is the api. There is no reason some whitelisting should be done on top of it.

Also increase bindgen version.

### CODE REVIEW

**Comment by ccouzens** [comment]
Thank you @NilsIrl.

I'm getting a warning when running the tests:
```
warning: `extern` block uses type `u128`, which is not FFI-safe
    --> /home/chris/Documents/git/github.com/ccouzens/leptonica-sys/target/debug/build/leptonica-sys-3634b718d278f931/out/bindings.rs:1448:10
     |
1448 |     ) -> u128;
     |          ^^^^ not FFI-safe
     |
     = note: `#[warn(improper_ctypes)]` on by default
     = note: 128-bit integers don't currently have a known stable ABI
```

Is it possible to prevent this without hiding it? I'll investigate too.

I think the reason I didn't do it this way initially is because I was worried about it including functions from the c-standard library like `printf`. But this doesn't seem to be a problem.

**Comment by ccouzens** [comment]
The functions generating these warnings are:

```
// part of <stdlib.h> 
extern "C" {
    pub fn strtold(
        __nptr: *const ::std::os::raw::c_char,
        __endptr: *mut *mut ::std::os::raw::c_char,
    ) -> u128;
}

// part of <stdlib.h> 
extern "C" {
    pub fn qecvt(
        __value: u128,
        __ndigit: ::std::os::raw::c_int,
        __decpt: *mut ::std::os::raw::c_int,
        __sign: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}

// part of <stdlib.h> 
extern "C" {
    pub fn qfcvt(
        __value: u128,
        __ndigit: ::std::os::raw::c_int,
        __decpt: *mut ::std::os::raw::c_int,
        __sign: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}

// part of <stdlib.h> 
extern "C" {
    pub fn qgcvt(
        __value: u128,
        __ndigit: ::std::os::raw::c_int,
        __buf: *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}

// part of <stdlib.h> 
extern "C" {
    pub fn qecvt_r(
        __value: u128,
        __ndigit: ::std::os::raw::c_int,
        __decpt: *mut ::std::os::raw::c_int,
        __sign: *mut ::std::os::raw::c_int,
        __buf: *mut ::std::os::raw::c_char,
        __len: usize,
    ) -> ::std::os::raw::c_int;
}

// part of <stdlib.h> 
extern "C" {
    pub fn qfcvt_r(
        __value: u128,
        __ndigit: ::std::os::raw::c_int,
        __decpt: *mut ::std::os::raw::c_int,
        __sign: *mut ::std::os::raw::c_int,
        __buf: *mut ::std::os::raw::c_char,
        __len: usize,
    ) -> ::std::os::raw::c_int;
}
```

I'll see if I can exclude stdlib and any other libraries.

**Comment by NilsIrl** [comment]
This seems to be a known issue

https://github.com/rust-lang/rust-bindgen/issues/1549

**Comment by NilsIrl** [comment]
> I think the reason I didn't do it this way initially is because I was worried about it including functions from the c-standard library like printf.

These functions are indeed included

It that's really a problem. [These](https://github.com/DanBloomberg/leptonica/blob/73c4f12f481d3110099de922c817f837726303a9/src/alltypes.h#L31-L33) could be removed

**Comment by ccouzens** [comment]
> It that's really a problem. These could be removed

Changing `wrapper.h` to be

```c
#define _STDLIB_H       1

#include <leptonica/allheaders.h>
```

Seems to exclude `stdlib.h`. The warning goes away, and the tests still pass

**Comment by ccouzens** [comment]
Actually, I'll merge it as is. The warnings don't show for dependent crates.

**Comment by ccouzens** [comment]
I've pushed this as version 0.3.0.

I'm currently updating tesseract-sys and tesseract-rs to use it.

**Comment by ccouzens** [comment]
> I didn't have access to the file format enums.

@NilsIrl, can you let me know one of the enums you need? I'll add a test so to make sure it doesn't get removed in future

**Comment by NilsIrl** [comment]
https://github.com/DanBloomberg/leptonica/blob/50c3c353f75b0a5c97b645b3c050dab66243ee20/src/imageio.h#L91-L112

**Pull request merged**
